server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev

aliyun:
  oss:
    file:
      endpoint: oss-cn-nanjing.aliyuncs.com
      key-id: LTAI5t6svFCu4P6xbYDW8chP
      key-secret: Bu7djODxYnwGrcok0d99fojgAGju2Q
      bucket-name: guli-edu-stein
